VNPOST.WebApplication/Areas/Se/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinTuc.Service.Se;

namespace TinTuc.WebApplication.Areas.Se.Controllers
{
    [Area("Se")]
    public class ArticleController : Controller
    {
        private readonly IArticlePublicService _articlePublicService;
        public ArticleController(IArticlePublicService articlePublicService)
        {
            _articlePublicService = articlePublicService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Detail(Guid id)
        {
            var article = _articlePublicService.GetById(id);
            var idCate = article.Model.Category.Id;
            var listArticle = _articlePublicService.GetArticleForCategory(idCate);
            ViewBag.articleDetail = article;
            ViewBag.listArticle = listArticle;
            return View();
        }
    }
}

VNPOST.WebApplication/Areas/Se/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinTuc.Service.Se;

namespace TinTuc.WebApplication.Areas.Se.Controllers
{
    [Area("Se")]
    public class CategoryController : Controller
    {
        private readonly ICategoryPublicService _categoryPublicService;
        private readonly IArticlePublicService _articlePublicService;

        public CategoryController(ICategoryPublicService categoryPublicService, IArticlePublicService articlePublicService) 
        {
            _categoryPublicService = categoryPublicService;
            _articlePublicService = articlePublicService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetCategory(Guid id)
        {
            ViewBag.ArticleForCategory = _categoryPublicService.GetArticleById(id);
            ViewBag.ArticleNearest = _articlePublicService.GetAll();
            ViewBag.AllCategory = _categoryPublicService.GetAllCategory();
            return View();
        }
    }
}

VNPOST.WebApplication/Areas/System/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TinTuc.Data.Entities.System;
using TinTuc.Service.Models;
using TinTuc.Service.Models.Request;
using TinTuc.Service.Models.Response;
using TinTuc.Service.System;

namespace TinTuc.WebApplication.Areas.System.Controllers
{
    [Area("System")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        public GetResponse<User> GetAll()
        {
            return _userService.GetAll();
        }
        [HttpPost]
        public UpdateResponse CreateOrUpdate(UpdateRequest<User> request)
        {
            _userService.CreateOrUpdate(request);
            return new UpdateResponse
            {
                Id = request.Model.Id,
                ResponseMessage = "Thành công",
                Status = ResponseStatus.Success
            };
        }
        [HttpGet]
        public GetResponse<User> GetUserById(Guid Id)
        {
            return _userService.GetById(Id);
        }
    }
}

VNPOST.WebApplication/Areas/System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<title>News - Administrator</title>

	<meta charset="utf-8">


	<link rel="stylesheet" href="~/Assets/System/fonts/fontawesome/css/fontawesome-all.min.css">

	<link rel="stylesheet" href="~/Assets/System/plugins/animation/css/animate.min.css">

	<link rel="stylesheet" href="~/Assets/System/plugins/data-tables/css/datatables.min.css">
	<link rel="stylesheet" href="~/Assets/System/css/style.css">

	@RenderSection("Css", required: false)
</head>

<body class="">
	<nav class="pcoded-navbar menupos-fixed ">
		<div class="navbar-wrapper ">
			<div class="navbar-brand header-logo">
				<a href="index-2.html" class="b-brand">
					<div class="b-bg">
						H
					</div>
					<span class="b-title">DHCNHN</span>
				</a>
				<a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
			</div>
			<div class="navbar-content scroll-div   ">
				<ul class="nav pcoded-inner-navbar ">
					<li class="nav-item pcoded-menu-caption">
						<label>Navigation</label>
					</li>
					<li data-username="dashboard default ecommerce sales Helpdesk ticket CRM analytics crypto project"
						class="nav-item">
						<a href="@Url.Action("Index","Home", new { area = "System"})" class="nav-link">
							<span class="pcoded-micon">
								<i class="feather icon-home"></i>
							</span><span class="pcoded-mtext">Dashboard</span>
						</a>
					</li>
					<li data-username="vertical horizontal box layout RTL fixed static collapse menu color icon dark background image"
						class="nav-item">
						<a href="@Url.Action("Index","Category", new { area = "System"})" class="nav-link">
							<span class="pcoded-micon">
								<i class="feather icon-layout"></i>
							</span><span class="pcoded-mtext">
								Category
							</span>
						</a>
					</li>
					<li data-username="vertical horizontal box layout RTL fixed static collapse menu color icon dark background image"
						class="nav-item">
						<a href="@Url.Action("Index","Article", new { area = "System"})" class="nav-link">
							<span class="pcoded-micon">
								<i class="feather icon-layout"></i>
							</span><span class="pcoded-mtext">
								Article
							</span>
						</a>
					</li>
					<li data-username="widget statistic data chart" class="nav-item ">
						<a href="@Url.Action("Index","User", new { area = "System"})" class="nav-link">
							<span class="pcoded-micon">
								<i class="feather icon-file-text"></i>
							</span><span class="pcoded-mtext">User</span><span class="pcoded-badge label label-success">100+</span>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<header class="navbar pcoded-header navbar-expand-lg navbar-light headerpos-fixed">
		<div class="m-header">
			<a class="mobile-menu" id="mobile-collapse1" href="#!"><span></span></a>
			<a href="index-2.html" class="b-brand">
				<div class="b-bg">
					H
				</div>
				<span class="b-title">HAUI</span>
			</a>
		</div>
		<a class="mobile-menu" id="mobile-header" href="#!">
			<i class="feather icon-more-horizontal"></i>
		</a>
		<div class="collapse navbar-collapse">
			<a href="#!" class="mob-toggler"></a>
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<div class="main-search">
						<div class="input-group">
							<input type="text" id="m-search" class="form-control" placeholder="Search . . .">
							<a href="#!" class="input-group-append search-close">
								<i class="feather icon-x input-group-text"></i>
							</a>
							<span class="input-group-append search-btn btn btn-primary">
								<i class="feather icon-search input-group-text"></i>
							</span>
						</div>
					</div>
				</li>
				<li>
					<div class="dropdown">
						<a class="dropdown-toggle" href="#" data-toggle="dropdown">
							<i class="icon feather icon-bell"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-right notification">
							<div class="noti-head">
								<h6 class="d-inline-block m-b-0">Notifications</h6>
								<div class="float-right">
									<a href="#!" class="m-r-10">mark as read</a>
									<a href="#!">clear all</a>
								</div>
							</div>
							<ul class="noti-body">
								<li class="n-title">
									<p class="m-b-0">NEW</p>
								</li>
								<li class="notification">
									<div class="media">
										<img class="img-radius" src="~/Assets/System/images/user/avatar-1.jpg"
											 alt="Generic placeholder image">
										<div class="media-body">
											<p>
												<strong>Administrator</strong><span class="n-time text-muted">
													<i class="icon feather icon-clock m-r-10"></i>5 min
												</span>
											</p>
											<p>New ticket Added</p>
										</div>
									</div>
								</li>
								<li class="n-title">
									<p class="m-b-0">EARLIER</p>
								</li>
								<li class="notification">
									<div class="media">
										<img class="img-radius" src="~/Assets/System/images/user/avatar-2.jpg"
											 alt="Generic placeholder image">
										<div class="media-body">
											<p>
												<strong>Joseph William</strong><span class="n-time text-muted">
													<i class="icon feather icon-clock m-r-10"></i>10 min
												</span>
											</p>
											<p>Prchace New Theme and make payment</p>
										</div>
									</div>
								</li>
								<li class="notification">
									<div class="media">
										<img class="img-radius" src="~/Assets/System/images/user/avatar-3.jpg"
											 alt="Generic placeholder image">
										<div class="media-body">
											<p>
												<strong>Sara Soudein</strong><span class="n-time text-muted">
													<i class="icon feather icon-clock m-r-10"></i>12 min
												</span>
											</p>
											<p>currently login</p>
										</div>
									</div>
								</li>
								<li class="notification">
									<div class="media">
										<img class="img-radius" src="~/Assets/System/images/user/avatar-1.jpg"
											 alt="Generic placeholder image">
										<div class="media-body">
											<p>
												<strong>Joseph William</strong><span class="n-time text-muted">
													<i class="icon feather icon-clock m-r-10"></i>30 min
												</span>
											</p>
											<p>Prchace New Theme and make payment</p>
										</div>
									</div>
								</li>
								<li class="notification">
									<div class="media">
										<img class="img-radius" src="~/Assets/System/images/user/avatar-3.jpg"
											 alt="Generic placeholder image">
										<div class="media-body">
											<p>
												<strong>Sara Soudein</strong><span class="n-time text-muted">
													<i class="icon feather icon-clock m-r-10"></i>1 hour
												</span>
											</p>
											<p>currently login</p>
										</div>
									</div>
								</li>
								<li class="notification">
									<div class="media">
										<img class="img-radius" src="~/Assets/System/images/user/avatar-1.jpg"
											 alt="Generic placeholder image">
										<div class="media-body">
											<p>
												<strong>Joseph William</strong><span class="n-time text-muted">
													<i class="icon feather icon-clock m-r-10"></i>2 hour
												</span>
											</p>
											<p>Prchace New Theme and make payment</p>
										</div>
									</div>
								</li>
							</ul>
							<div class="noti-footer">
								<a href="#!">show all</a>
							</div>
						</div>
					</div>
				</li>
				<li><a href="#!" class="displayChatbox"><i class="icon feather icon-mail"></i></a></li>
				<li>
					<div class="dropdown drp-user">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<i class="icon feather icon-settings"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-right profile-notification">
							<div class="pro-head">
								<img src="~/Assets/System/images/user/avatar-1.jpg" class="img-radius"
									 alt="User-Profile-Image">
								<span>Administrator</span>
								<a asp-area="System" asp-controller="Login" asp-action="SignIn" class="dud-logout" title="Logout">
									<i class="feather icon-log-out"></i>
								</a>
							</div>
							<ul class="pro-body">
								<li>
									<a href="#!" class="dropdown-item">
										<i class="feather icon-settings"></i>
										Settings
									</a>
								</li>
								<li>
									<a href="#!" class="dropdown-item"><i class="feather icon-user"></i> Profile</a>
								</li>
								<li>
									<a href="message.html" class="dropdown-item">
										<i class="feather icon-mail"></i> My
										Messages
									</a>
								</li>
								<li>
									<a href="auth-signin.html" class="dropdown-item">
										<i class="feather icon-lock"></i>
										Lock Screen
									</a>
								</li>
							</ul>
						</div>
					</div>
				</li>
			</ul>
		</div>
	</header>
	<section class="pcoded-main-container">
		<div class="pcoded-wrapper">
			<div class="pcoded-content">
				<div class="pcoded-inner-content">
					<div class="main-body">
						<div class="page-wrapper">
							<div class="row">
								<div class="col-sm-12">
									@RenderBody()
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<script src="~/Assets/System/plugins/jquery/js/jquery-3.5.1.min.js"></script>
	<script src="~/Assets/System/js/vendor-all.min.js"></script>
	<script src="~/Assets/System/plugins/bootstrap/js/bootstrap.min.js"></script>
	<script src="~/Assets/System/js/pcoded.min.js"></script>
	@*<script src="~/Assets/System/js/menu-setting.min.js"></script>*@

	<script src="~/Assets/System/plugins/data-tables/js/datatables.min.js"></script>
	<script src="~/Assets/System/js/pages/data-basic-custom.js"></script>
	<script src="~/Assets/System/plugins/sweetalert/js/sweetalert.min.js"></script>


	@RenderSection("Scripts", required: false)
</body>
</html>

VNPOST.WebApplication/Areas/System/Views/Shared/_Menubar.cshtml
@{
	ViewData["Title"] = "_Menubar";
	Layout = null;
}

<div class="site-menubar">
	<div class="site-menubar-body">
		<div>
			<div>
				<ul class="site-menu" data-plugin="menu">
					<li class="site-menu-category">TinTuc</li>

					<li class="site-menu-item has-sub">
						<a href="@Url.Action("Index","Home",new{ area = "System"})">
							<i class="site-menu-icon wb-dashboard" aria-hidden="true"></i>
							<span class="site-menu-title">Homepage</span>
							<div class="site-menu-badge">
								<span class="badge badge-pill badge-success">3</span>
							</div>
						</a>
					</li>
					<li class="site-menu-item has-sub">
						<a href="@Url.Action("Index","Category",new{ area = "System"})">
							<i class="site-menu-icon wb-layout" aria-hidden="true"></i>
							<span class="site-menu-title">Category</span>
							@*<span class="site-menu-arrow"></span>*@
						</a>
					</li>
					<li class="site-menu-item has-sub">
						<a href="@Url.Action("Index","Article",new{ area = "System"})">
							<i class="site-menu-icon wb-file" aria-hidden="true"></i>
							<span class="site-menu-title">Articles</span>
							@*<span class="site-menu-arrow"></span>*@
						</a>
					</li>
				</ul>

				@*<div class="site-menubar-section">
						<h5>
							Milestone
							<span class="float-right">30%</span>
						</h5>
						<div class="progress progress-xs">
							<div class="progress-bar active" style="width: 30%;" role="progressbar"></div>
						</div>
						<h5>
							Release
							<span class="float-right">60%</span>
						</h5>
						<div class="progress progress-xs">
							<div class="progress-bar progress-bar-warning" style="width: 60%;" role="progressbar"></div>
						</div>
					</div>*@
			</div>
		</div>
	</div>

	<div class="site-menubar-footer">
		<a href="javascript: void(0);" class="fold-show" data-placement="top" data-toggle="tooltip"
		   data-original-title="Settings">
			<span class="icon wb-settings" aria-hidden="true"></span>
		</a>
		<a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Lock">
			<span class="icon wb-eye-close" aria-hidden="true"></span>
		</a>
		<a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Logout">
			<span class="icon wb-power" aria-hidden="true"></span>
		</a>
	</div>
</div>